# Generated by Django 2.2.3 on 2019-08-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Enter URL for article', max_length=150)),
                ('text', models.CharField(help_text='Enter article text', max_length=25000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.IntegerField()),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Article')),
            ],
        ),
    ]
