# Generated by Django 2.2.3 on 2019-08-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_articlebias_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(help_text='Enter article text', max_length=50000),
        ),
        migrations.AlterField(
            model_name='articlebias',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
